[package]
name = "rowscript-compiler"
version = "0.1.0"
edition = "2021"
authors = ["RowScript developers"]
license = "MIT"
description = "RowScript compiler"
readme = "README.md"
categories = ["development-tools"]
repository = "https://github.com/rowscript/rowscript"

[dependencies]
tree-sitter = "0.20.0"
thiserror = "1.0.30"
rowscript-core = { path = "../rowscript-core" }

[build-dependencies]
cc = "*"
