[package]
name = "rowscript-core"
version = "1.0.0-alpha.6"
edition = "2024"

[dependencies]
strum = { version = "0.27.2", features = ["derive"] }
ustr = "1.1.0"
serde_json = "1.0.145"
chumsky = { version = "1.0.0-alpha.8", features = ["pratt"] }
cranelift = "0.125.3"
cranelift-native = "0.125.3"
cranelift-module = "0.125.3"
cranelift-jit = "0.125.3"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "eval"
harness = false
